name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "best1234567890.xyz"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.best1234567890.xyz", custom_domain = true },
  { pattern = "quay.best1234567890.xyz", custom_domain = true },
  { pattern = "gcr.best1234567890.xyz", custom_domain = true },
  { pattern = "k8s-gcr.best1234567890.xyz", custom_domain = true },
  { pattern = "k8s.best1234567890.xyz", custom_domain = true },
  { pattern = "ghcr.best1234567890.xyz", custom_domain = true },
  { pattern = "cloudsmith.best1234567890.xyz", custom_domain = true },
]
# routes = [
#   { pattern = "docker.best1234567890.xyz", custom_domain = true },
#   { pattern = "quay.best1234567890.xyz", custom_domain = true },
#   { pattern = "gcr.best1234567890.xyz", custom_domain = true },
#   { pattern = "k8s-gcr.best1234567890.xyz", custom_domain = true },
#   { pattern = "k8s.best1234567890.xyz", custom_domain = true },
#   { pattern = "ghcr.best1234567890.xyz", custom_domain = true },
#   { pattern = "cloudsmith.best1234567890.xyz", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.best1234567890.xyz", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
